# Docker Compose file for nzb stack
---
services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=${uid}
      - PGID=${gid}
      - TZ=${tz}
    volumes:
      - ${rootConf}/sabnzbd:/config
      - ${rootMedia}:/storage #optional
    ports:
      - 8080:8080 # 8080 is default
    restart: unless-stopped
    network_mode: bridge
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${uid}
      - PGID=${gid}
      - TZ=${tz}
    volumes:
      - ${rootConf}/sonarr:/config
      - ${rootMedia}:/storage #optional
    ports:
      - 8989:8989 # 8989 is default
    restart: unless-stopped
    network_mode: bridge
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${uid}
      - PGID=${gid}
      - TZ=${tz}
    volumes:
      - ${rootConf}/radarr:/config
      - ${rootMedia}:/storage #optional
    ports:
      - 7878:7878 # 7878 is default
    restart: unless-stopped
    network_mode: bridge
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=${uid}
      - PGID=${gid}
      - TZ=${tz}
    volumes:
      - ${rootConf}/lidarr:/config
      - ${rootMedia}:/media #optional
    ports:
      - 8686:8686 # 8686 is default
    restart: unless-stopped
    network_mode: bridge
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=${uid}
      - PGID=${gid}
      - TZ=${tz}
    volumes:
      - ${rootConf}/bazarr:/config
      - ${rootMedia}:/storage #optional
    ports:
      - 6767:6767 # 6767 is default
    restart: unless-stopped
    network_mode: bridge
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${uid}
      - PGID=${gid}
      - TZ=${tz}
    volumes:
       - ${rootConf}/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
